[package]
authors = ["Trey Dempsey <trey.dempsey@gmail.com>"]
categories = ["database", "asynchronous", "web-programming"]
description = "Proc macro implemtation for sqlx-crud to implement Create, Read, Update, and Delete (CRUD) methods on SQLx for you ğŸª„ ğŸ“– ğŸ“ âŒ"
documentation = "https://docs.rs/sqlx-crud"
edition = "2021"
keywords = ["sqlx", "orm", "crud", "database"]
license = "MIT"
name = "sqlx-crud-macros"
repository = "https://github.com/treydempsey/sqlx-crud"
version = "0.4.0"

[lib]
proc-macro = true

[dependencies]
Inflector = "0.11"
proc-macro2 = "1.0"
quote = "1.0"
syn = {version = "2.0", features = ["full"]}

[features]
default_mysql = []
